version: '3.5'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: TransportCompany
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_PORT: 3306
      PMA_HOST: mysql
    ports:
      - "5050:80"

volumes:
  mysql_data:

networks:
  docker-network:
    external: false